# Generated by Django 4.2.5 on 2023-09-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='self_edu',
            name='date',
            field=models.DateField(blank=True, default='2020-01-01', null=True),
        ),
    ]
