# Generated by Django 4.2.4 on 2023-08-13 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='main_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images/')),
                ('done_at', models.DateField(blank=True, null=True)),
                ('demo', models.URLField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'ordering': ['done_at'],
            },
        ),
        migrations.CreateModel(
            name='web_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images/')),
                ('done_at', models.DateField(blank=True, null=True)),
                ('demo', models.URLField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('status', models.CharField(max_length=10, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='project_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.web_project')),
            ],
        ),
    ]
