# Generated by Django 4.2.4 on 2023-09-04 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='web_project',
            options={'ordering': ['done_at']},
        ),
    ]
