# Generated by Django 4.2.4 on 2023-09-05 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_web_project_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_status',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.main_project'),
        ),
    ]
